-- Active: 1742232558313@@127.0.0.1@3306@ENGLISH_CENTER_DATABASE
-------- Delete exist database

USE ENGLISH_CENTER_DATABASE;
DROP DATABASE ENGLISH_CENTER_DATABASE;





--------- Create new database
CREATE DATABASE ENGLISH_CENTER_DATABASE;
USE ENGLISH_CENTER_DATABASE;

CREATE TABLE PERSON (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100) UNIQUE,
    PHONE_NUMBER VARCHAR(15),
    DATE_OF_BIRTH DATE,
    ROLE ENUM('STUDENT', 'STAFF') DEFAULT 'STUDENT',
    PASSWORD VARCHAR(255)
);

CREATE TABLE STUDENT (
    ID INT,
    ENROLL_DATE DATE,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID) REFERENCES PERSON(ID)
);

CREATE TABLE STAFF (
    ID INT PRIMARY KEY,
    HIRE_DAY DATE,
    STAFF_TYPE ENUM('TEACHER', 'ADMIN', 'ACCOUNTANT'),
    FOREIGN KEY (ID) REFERENCES PERSON(ID)
);

CREATE TABLE COURSE (
    COURSE_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    START_DATE DATE,
    END_DATE DATE,
    MIN_STU INT,
    MAX_STU INT
);

CREATE TABLE TUITION (
    T_ID INT PRIMARY KEY AUTO_INCREMENT,
    PRICE DECIMAL(12, 0) NOT NULL,
    TYPE ENUM('UNPAID', 'CARD', 'TRANSFER', 'CASH') NOT NULL,
    DESCRIPTION TEXT,
    STATUS ENUM('UNPAID', 'PAID', 'DEFERRED') DEFAULT 'UNPAID'
);

CREATE TABLE STUDENT_COURSE (
    STUDENT_ID INT,
    COURSE_ID INT,
    PAYMENT_ID INT,
    PRIMARY KEY (STUDENT_ID, COURSE_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
    FOREIGN KEY (PAYMENT_ID) REFERENCES TUITION(T_ID)
);

CREATE TABLE TEACHER_COURSE (
    TEACHER_ID INT,
    COURSE_ID INT,
    ROLE ENUM('LECTURER', 'ASSISTANT') NOT NULL,
    PRIMARY KEY (TEACHER_ID, COURSE_ID),
    FOREIGN KEY (TEACHER_ID) REFERENCES STAFF(ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);

CREATE TABLE ASSIGNMENT (
    AS_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    FILE VARCHAR(255), -- link
    START_DATE DATETIME,
    END_DATE DATETIME,
    COURSE_ID INT,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);

CREATE TABLE DOCUMENT (
    DOC_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    FILE VARCHAR(255),  -- link
    COURSE_ID INT,
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
);

CREATE TABLE SUBMITION (
    STUDENT_ID INT,
    AS_ID INT,
    SUBMIT_DATE DATETIME,
    DESCRIPTION TEXT,
    FILE VARCHAR(255),  
    SCORE DECIMAL(5,2),  
    PRIMARY KEY (STUDENT_ID, AS_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
    FOREIGN KEY (AS_ID) REFERENCES ASSIGNMENT(AS_ID)
);

--------------- Constraint 


--------------- Insert data

-- Insert into PERSON table
INSERT INTO PERSON (NAME, EMAIL, PHONE_NUMBER, DATE_OF_BIRTH, ROLE, PASSWORD)
VALUES 
('Alice Johnson', 'alice@example.com', '123-456-7890', '2000-05-15', 'STUDENT', 'hashedpassword1'),
('Bob Smith', 'bob@example.com', '234-567-8901', '1985-09-20', 'STAFF', 'hashedpassword2'),
('Charlie Davis', 'charlie@example.com', '345-678-9012', '1995-02-10', 'STUDENT', 'hashedpassword3'),
('ADMIN ROOT', 'root@gmail.com', '456-789-0123', '1978-11-03', 'STAFF', '$2b$10$aqT9n/DCyJCSvSwbTsL.VeOjvBcnjHZDQSZvv/Bd7Mm/9zgcOfAbe'),
('Edward Blake', 'edward@example.com', '567-890-1234', '1998-04-12', 'STUDENT', 'hashedpassword5'),
('Fiona Grey', 'fiona@example.com', '678-901-2345', '1982-12-05', 'STAFF', 'hashedpassword6'),
('George King', 'george@example.com', '789-012-3456', '2001-07-30', 'STUDENT', 'hashedpassword7'),
('Helen Wood', 'helen@example.com', '890-123-4567', '1975-03-18', 'STAFF', 'hashedpassword8'),
('Ian Sharp', 'ian@example.com', '901-234-5678', '1990-06-25', 'STUDENT', 'hashedpassword9'),
('Julia Stone', 'julia@example.com', '012-345-6789', '1987-01-09', 'STAFF', 'hashedpassword10');

-- Insert into STUDENT table
INSERT INTO STUDENT (ID, ENROLL_DATE)
VALUES 
(1, '2019-09-01'),
(3, '2021-01-15'),
(5, '2020-09-01'),
(7, '2022-01-10'),
(9, '2023-03-05');

-- Insert into STAFF table
INSERT INTO STAFF (ID, HIRE_DAY, STAFF_TYPE)
VALUES 
(2, '2010-06-10', 'TEACHER'),
(4, '2015-08-25', 'ADMIN'),
(6, '2012-02-14', 'ACCOUNTANT'),
(8, '2008-11-30', 'TEACHER'),
(10, '2017-04-20', 'ADMIN');